In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [3]:
a= np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0] = 10
print(a)

[10  2  3  4  5  6]


arrayのsliceは元の配列のビューを返す
コピーしないので元の配列にアクセスでき変更することが可能

In [5]:
b = a[3:]
b


array([4, 5, 6])

In [6]:
b[1] = 50
a

array([10,  2,  3,  4, 50,  6])

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[2, 1]

np.int64(8)

## Array attributes

In [9]:
a.ndim

2

In [10]:
a.shape

(3, 3)

In [11]:
len(a.shape) == a.ndim

True

In [12]:
a.size

9

In [13]:
import math
a.size == math.prod(a.shape)

True

In [14]:
a.dtype

dtype('int64')

## How to create a basic array

In [15]:
np.zeros(2)

array([0., 0.])

In [16]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.empty((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [21]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

## Adding, removing, and sorting elements

In [22]:
arr = np.array([2, 3, 1, 9, 4, 6, 2, 8])
np.sort(arr)

array([1, 2, 2, 3, 4, 6, 8, 9])

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [24]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [26]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
x[0:, 1:]

array([[2],
       [4]])

## How do you know the shape and size of an array?

In [28]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [29]:
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
array_example.shape

(3, 2, 4)

## Can you reshape an array?

In [32]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
np.reshape(a, shape=(1, 6), order="C")

array([[0, 1, 2, 3, 4, 5]])

## How to convert a 1D array into a 2D array
(how to add a new axis to an array)

In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
a2 = a[np.newaxis, :]
print(a2)

[[1 2 3 4 5 6]]


In [37]:
a2.shape

(1, 6)

In [41]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [42]:
print(row_vector)

[[1 2 3 4 5 6]]


In [45]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [49]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Indexing and slicing

In [50]:
data = np.array([1, 2, 3])
data[1]

np.int64(2)

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 8])

[1 2 3 4 5 6 7]


In [54]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [55]:
print(a[a % 2 == 0])

[ 2  4  6  8 10 12]


In [60]:
print(a[(a > 2) & (a < 11)])

[ 3  4  5  6  7  8  9 10]


In [62]:
print((a > 5) | (a % 2 == 0))

[[False  True False  True]
 [False  True  True  True]
 [ True  True  True  True]]


In [63]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [67]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [69]:
list_of_coordinates = list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord[1])

0
1
2
3


In [70]:
print(a[b])

[1 2 3 4]


In [71]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data

In [72]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [74]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [75]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [76]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [78]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [85]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [86]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [88]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [89]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
b2 = a.copy()

In [94]:
b2[0] = 49
b2

array([[49, 49, 49, 49],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [95]:
data = np.array([1, 2])
ones = np.ones(2, dtype=np.int_)
data + ones

array([2, 3])

In [101]:
data / data

array([1., 1.])

In [102]:
data.sum()

np.int64(3)

In [103]:
b = np.array([[1, 1], [2, 2]])

In [104]:
b.sum(axis=0)

array([3, 3])

In [105]:
b.sum(axis=1)

array([2, 4])

## Broadcasting

In [107]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

## More useful array operations

In [108]:
data = np.array([1, 2, 3])
data.max()

np.int64(3)

In [109]:
data.min()

np.int64(1)

In [110]:
data.sum()

np.int64(6)

In [111]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [112]:
a.sum()

np.float64(4.8595784)

In [113]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

## Creating matrices

In [114]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
data[0:3, 1]

array([2, 4, 6])

In [117]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [118]:
data.max(axis=0)

array([5, 6])

In [119]:
data.max(axis=1)

array([2, 5, 6])

In [121]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
# dame size
data + ones

array([[2, 3],
       [4, 5]])

In [122]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1, 1])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [123]:
np.ones(3)

array([1., 1., 1.])

In [124]:
np.zeros(3)

array([0., 0., 0.])

In [125]:
rng = np.random.default_rng() # the simplest way to generate random numbers
rng.random(3)

array([0.35691547, 0.40299873, 0.82036899])

In [126]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [128]:
rng.random((2,5))

array([[0.39122711, 0.45414934, 0.08632718, 0.4714033 , 0.97354344],
       [0.29940523, 0.90551241, 0.41127257, 0.99307176, 0.70237107]])

## Generating random numbers

In [ ]:
# between 0 and 4
rng.integers(5, size=(2, 4))

array([[3, 0, 0, 3],
       [1, 0, 2, 2]])

## How to get unique items and counts

In [131]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [132]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [133]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [143]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [135]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [136]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [140]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_index=True, return_counts=True
)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
print(indices)

[0 1 2]


In [142]:
print(occurrence_count)

[2 1 1]


## Transposing and reshaping a matrix